### ISSUE TITLE
TODO для таблицы

### ISSUE THREAD

**Issue by Kublyakov** [Kublyakov/kublyakov.github.io#1]
- [x] При корректной отправке формы очищать её содержимое, во избежание повторных нажатий и дублирования таблицы.
- [ ] Либо при отправке формы существующую таблицу заменять на новую. Разобраться почему сейчас дублируется таблица в любом случае.
- [ ] У целых чисел на входе присутствует дробная часть в виде трех нулей. Отсекать ее.
- [ ] Прикрутить экспорт в xls или otd файл. (http://javascript.ru/forum/jquery/43101-ehksport-html-table-v-excel.html)
- [ ] Прикрутить кнопку копирования содержимого ячейки.
